/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.galactis.od;

import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        Map<String, String> argMap = CommandParser.parse(args);
        System.out.println(argMap);
        String model = null;
        boolean inherit = false;
        if (argMap.get("n") != null) {
            model = argMap.get("n");
        } else if (argMap.get("i") != null) {
            model = argMap.get("i");
            inherit = true;
        }

        if (model != null) {
            ModelGenerator.create(model, argMap.get("d"), argMap.get("g"), inherit);
            if (argMap.get("f") != null) {
                ModelGenerator.addFields(model, argMap.get("f"));
            }
            if (!inherit && argMap.get("v") != null) {
                ViewGenerator.create(model, argMap.get("v"));
            }            
        }
        if (argMap.get("m") != null) {
            MenuGenerator.create(model, argMap.get("m"));
        }
    }
}
