/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.galactis.od;

import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        Map<String, String> argMap = CommandParser.parse(args);
        System.out.println(argMap);

        if (argMap.get("n") != null) {
            ModelGenerator.create(argMap.get("n"), argMap.get("d"), argMap.get("g"), argMap.get("i") != null);
            if (argMap.get("f") != null) {
                ModelGenerator.addFields(argMap.get("n"), argMap.get("f"));
            }
            if (argMap.get("v") != null) {
                ViewGenerator.create(argMap.get("n"), argMap.get("v"));
            }
        }
    }
}
